apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: spoke-aks-prod
  namespace: capi-system
  labels:
    team: platform
    env: prod
    cost-center: core
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    services:
      cidrBlocks: ["10.96.0.0/12"]
  topology:
    class: spoke-aks
    version: "v1.30.0"
    controlPlane:
      replicas: 3
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: 3
