#!/bin/bash

echo "🚀 AI Agents Dashboard - GitOps Infrastructure"
echo "=============================================="
echo ""
echo "📊 Dashboard is now running at: http://localhost:8081"
echo "🔧 Backend API is available at: http://localhost:5000"
echo ""
echo "🤖 Features Available:"
echo "   • Real-time AI agent monitoring"
echo "   • System metrics and resource usage"
echo "   • Skills distribution overview"
echo "   • Activity feed with recent events"
echo "   • RAG-powered chatbot assistant"
echo ""
echo "🧠 Chatbot Commands to try:"
echo "   • 'What agents are running?'"
echo "   • 'Tell me about the cluster'"
echo "   • 'What skills are available?'"
echo "   • 'How is the performance?'"
echo "   • 'What does this dashboard do?'"
echo ""
echo "🔍 API Endpoints:"
echo "   • GET  http://localhost:5000/api/health"
echo "   • GET  http://localhost:5000/api/agents"
echo "   • GET  http://localhost:5000/api/metrics"
echo "   • GET  http://localhost:5000/api/skills"
echo "   • GET  http://localhost:5000/api/activity"
echo "   • POST http://localhost:5000/api/rag/query"
echo ""
echo "🛠️ Management Commands:"
echo "   • Check pods: kubectl get pods -n ai-infrastructure"
echo "   • Check services: kubectl get svc -n ai-infrastructure"
echo "   • View logs: kubectl logs -n ai-infrastructure deployment/dashboard-backend"
echo "   • Stop dashboard: Ctrl+C (port-forwarding processes)"
echo ""
echo "🌐 Opening dashboard in your browser..."

# Open the dashboard
open http://localhost:8081

echo "✅ Dashboard deployed successfully!"
echo ""
echo "💡 The dashboard includes:"
echo "   • Live system metrics from Kubernetes cluster"
echo "   • Real-time AI agent status and performance"
echo "   • Interactive RAG chatbot for system queries"
echo "   • Skills and activity monitoring"
echo "   • Modern responsive UI with real-time updates"
