apiVersion: v1
kind: Service
metadata:
  name: dashboard-backend-service
  namespace: ai-infrastructure
spec:
  selector:
    run: dashboard-backend-real
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
