apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alerts/commit-status.yaml
  - alerts/grafana-events.yaml
  - alerts/on-call.yaml
  - providers/github.yaml
  - providers/grafana.yaml
  - providers/slack.yaml
