apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai-infrastructure

resources:
- ./memory-selector
- ./standalone-backend
- ./ade

commonLabels:
  layer: ai-agents
  managed-by: gitops
