apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-key-vault
spec:
  provider:
    azurekv:
      vaultUrl: "https://YOUR-KEYVAULT-NAME.vault.azure.net"
      authType: WorkloadIdentity
