---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: karpenter-metrics
  namespace: karpenter
  labels:
    app: karpenter
    component: monitoring
    demo: karpenter-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: karpenter
  namespaceSelector:
    matchNames:
    - karpenter
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    honorLabels: true
---
apiVersion: v1
kind: Service
metadata:
  name: karpenter-metrics
  namespace: karpenter
  labels:
    app: karpenter
    component: monitoring
    app.kubernetes.io/name: karpenter
spec:
  selector:
    app.kubernetes.io/name: karpenter
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
