apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: main-network
spec:
  description: platform network
  autoCreateSubnetworks: false
  routingConfig:
    routingMode: REGIONAL
