apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: default
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: local-root-password
  MYSQL_DATABASE: sampledb
  MYSQL_USER: sampleuser
  MYSQL_PASSWORD: samplepass
