replicas: 2

image:
  pullPolicy: IfNotPresent

provider:
  packages: []

args:
  - --dangerous-disable-forward-rotation

rbac:
  enable: true

metrics:
  enable: true
  serviceMonitor:
    enabled: true

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

networkPolicy:
  enabled: true
  egress:
    - to: []
      ports:
        - protocol: TCP
          port: 443
