apiVersion: platform.example.com/v1alpha1
kind: Network
metadata:
  name: prod-network
  namespace: platform
  labels:
    team: platform
    env: production
    cost-center: platform
spec:
  compositionSelector:
    matchLabels:
      provider: aws
  cidr: 10.0.0.0/16
  region: us-east-1
  subnetCidrs:
    - 10.0.1.0/24
    - 10.0.2.0/24
    - 10.0.3.0/24
