resources:
  - ../../core/resources/tenants/azure/network
  - ../../core/resources/tenants/azure/clusters
  - ../../core/resources/tenants/azure/workloads
  - local-emulator
patchesStrategicMerge:
  - patches/vnet-overrides.yaml
  - patches/aks-overrides.yaml
