apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcluster-gke
  labels:
    provider: gcp
    platform.example.com/xrd: xcluster
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: XCluster
  resources:
    - name: gke-cluster
      base:
        apiVersion: container.gcp.crossplane.io/v1beta2
        kind: Cluster
        spec:
          forProvider:
            location: us-central1
            initialNodeCount: 3
            removeDefaultNodePool: false
            minMasterVersion: "1.30.0"
          providerConfigRef:
            name: gcp-provider
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.location
        - type: FromCompositeFieldPath
          fromFieldPath: spec.kubernetesVersion
          toFieldPath: spec.forProvider.minMasterVersion
        - type: FromCompositeFieldPath
          fromFieldPath: spec.nodeCount
          toFieldPath: spec.forProvider.initialNodeCount
