apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- azurite.yaml
- azure-functions-emulator.yaml
- azure-sql-emulator.yaml
- cosmos-emulator.yaml
- eventhubs-emulator.yaml
- localstack-azure.yaml
- servicebus-emulator.yaml
