apiVersion: containerservice.azure.com/v1beta20231001
kind: ManagedCluster
metadata:
  name: workload-cluster
spec:
  location: ${LOCATION}
  owner:
    name: ${RESOURCE_GROUP}
  sku:
    name: Base
    tier: Free
  identity:
    type: SystemAssigned
  kubernetesVersion: 1.27.0
  networkProfile:
    networkPlugin: azure
    serviceCidr: 10.0.0.0/16
    dnsServiceIP: 10.0.0.10
    dockerBridgeCidr: 172.17.0.1/16
  agentPoolProfiles:
  - name: agentpool
    count: 3
    vmSize: Standard_D2_v2
    osType: Linux
    mode: System
