apiVersion: v1
kind: ServiceAccount
metadata:
  name: kcc-controller-manager
  namespace: kcc-system
  annotations:
    iam.gke.io/gcp-service-account: kcc-controller-manager@${PROJECT_ID}.iam.gserviceaccount.com
