apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xcluster-eks
  labels:
    provider: aws
    platform.example.com/xrd: xcluster
spec:
  compositeTypeRef:
    apiVersion: platform.example.com/v1alpha1
    kind: XCluster
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
    - name: eks-cluster
      base:
        apiVersion: eks.aws.crossplane.io/v1beta1
        kind: Cluster
        spec:
          forProvider:
            region: us-east-1
            version: "1.30"
            roleArnSelector:
              matchLabels:
                role: eks-cluster
            resourcesVpcConfig:
              - endpointPublicAccess: false
                endpointPrivateAccess: true
                subnetIdRefs: []     # patched from networkRef
          deletionPolicy: Orphan
          providerConfigRef:
            name: aws-provider
          writeConnectionSecretToRef:
            namespace: crossplane-system
            name: ""
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.region
          toFieldPath: spec.forProvider.region
        - type: FromCompositeFieldPath
          fromFieldPath: spec.kubernetesVersion
          toFieldPath: spec.forProvider.version
        - type: FromCompositeFieldPath
          fromFieldPath: spec.deletionPolicy
          toFieldPath: spec.deletionPolicy
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: spec.writeConnectionSecretToRef.name
          transforms:
            - type: string
              string:
                fmt: "%s-kubeconfig"
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.endpoint
          toFieldPath: status.endpoint
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.status
          toFieldPath: status.phase
