apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phoenix-storage-pvc
  namespace: staging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
