apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: network-infra
  namespace: flux-system
resources:
  - platform-namespace.yaml
  - network-prod.yaml
labels:
  - pairs:
      managed-by: flux
      component: network-infra
      tier: infrastructure
      platform: multi-cluster-gitops
