apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: aws-ack-controllers
  namespace: flux-system
resources:
  - namespace.yaml
  - ec2-controller.yaml
  - eks-controller.yaml
  - iam-controller.yaml
