apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app: argocd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-server
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      containers:
        - name: argocd-server
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - sleep 3600
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "20m"
              memory: "64Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  selector:
    app: argocd-server
  ports:
    - port: 80
      targetPort: 80
