apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: YOUR_PROJECT_ID
      auth:
        workloadIdentity:
          clusterLocation: us-central1   # Replace with spoke region
          clusterName: YOUR_CLUSTER_NAME
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
